productsRoot:
  get:
    summary: Ambil semua Produk
    responses:
      200:
        description: Berhasil mengembalikan semua Produk
  post:
    summary: Tambah produk baru
    responses:
      201:
        description: Produk berhasil ditambahkan

productsWithId:
  get:
    summary: Ambil produk berdasarkan id
    responses:
      200:
        description: Berhasil mengembalikan produk yang sesuai id
  put:
    summary: update produk berdasarkan id
    responses:
      200:
        description: Berhasil update produk yang sesuai id
  delete:
    summary: delete produk berdasarkan id
    responses:
      200:
        description: Berhasil menghapus produk yang sesuai id
